version: '3.8'
services:
  product_store_db:
    image: postgres:14
    container_name: product_store_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: product_store_db
      POSTGRES_USER: kaitanov4
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
